on: [push, pull_request]
name: Check Commit
jobs:
  check_commit:
    name: Check Commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.18.0'
    - name: install checkers
      run: |
        go get honnef.co/go/tools/cmd/staticcheck
        go get golang.org/x/lint/golint
        go get github.com/client9/misspell/cmd/misspell
    - name: check
      run: make check
